Fix licenses and package tck instruction
eclipse/microprofile-health pull request #313
Opened 2021-09-16 10:55 UTC by Emily-Jiang

2021-09-16 10:57 UTC, Emily-Jiang commented
The licenses for TCKs need a marker file `tck` and the instruction needs to be called README.adoc to be packaged.

2021-09-16 10:58 UTC, Emily-Jiang commented
You can test it out using `-Drelease.revision=Final `to verify all licenses would appear correctly on the final release.

2021-09-16 11:23 UTC, xstefank requested changes
@Emily-Jiang so the licenses are now handled in the parent IIUC, right?

2021-09-16 11:23 UTC, xstefank commented on tck/src/main/resources/META-INF/NOTICE
> +==  Version 2.0, in this case for Microprofile Config                  ==
@Emily-Jiang this is the health repository ;)

2021-09-16 14:21 UTC, xstefank commented
@Emily-Jiang this now includes Eclipse license for both Draft and Final revisions. Is this expected going forward?

2021-09-16 22:17 UTC, Emily-Jiang commented
@xstefank the api jar should always contain the apache license while tck jar should contain Eclipse Foundation license for the final release. You can compare the jars with the previously released 3.0 version.

2021-09-17 13:54 UTC, xstefank approved these changes

2021-09-17 13:54 UTC, merged